name: "Update Flake Inputs"
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20221014_3093bd3/install
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # flakes don't work on shallow clones
      - name: git-setup
        run: |
          git config --global user.name 'Github Actions Are Bad'
          git config --global user.email 'dockerpocalypse@kubernetes.com'
      - name: update-flake-inputs
        run: |
          set -xeuo pipefail
          nix flake update --commit-lock-file
      - name: build-flake
        run: |
          set -xeuo pipefail
          nix build
      - name: push
        run: |
          git push origin HEAD

